#!/bin/bash
sudo pacman -Sy --needed base-devel --noconfirm;

which paru > /dev/null 2>&1;

if [ $? -ne 0 ];
then
  git clone https://aur.archlinux.org/paru-bin.git;
  cd paru-bin;
  makepkg -si --noconfirm;
  cd ..;
  rm -rf paru-bin;
fi

paru -S paru-bin --needed --noconfirm --skipreview;

grep -qxF '[universe]' /etc/pacman.conf || sudo tee -a /etc/pacman.conf >/dev/null << 'EOF'
[universe]
Server = https://universe.artixlinux.org/$arch
Server = https://mirror1.artixlinux.org/universe/$arch
Server = https://mirror.pascalpuffke.de/artix-universe/$arch
Server = https://artixlinux.qontinuum.space/artixlinux/universe/os/$arch
Server = https://mirror1.cl.netactuate.com/artix/universe/$arch
Server = https://ftp.crifo.org/artix-universe/
EOF

sudo pacman -Sy --needed artix-archlinux-support --noconfirm

grep -qxF '# Arch' /etc/pacman.conf || sudo tee -a /etc/pacman.conf >/dev/null << 'EOF'

# Arch
[extra]
Include = /etc/pacman.d/mirrorlist-arch

[community]
Include = /etc/pacman.d/mirrorlist-arch

[multilib]
Include = /etc/pacman.d/mirrorlist-arch
EOF

paru -S --needed --noconfirm --skipreview \
alacritty \
brave-bin \
exa \
fish \
gdm-runit \
gnome-control-center \
gnome-keyring \
gnome-shell \
gnome-tweaks \
ispell \
openssh-runit \
neofetch \
pyenv \
tfenv \
ttf-fira-code \
yadm \
yamllint;

if [[ $(cat /etc/passwd | grep epost | awk -F: '{print $7}') != '/usr/bin/fish' ]];
then
  chsh -s /usr/bin/fish;
fi

if [ ! -L /run/runit/service/sshd ];
then
  sudo ln -s /etc/runit/sv/sshd /run/runit/service/
fi

if [ ! -L /run/runit/service/gdm ];
then
  sudo ln -s /etc/runit/sv/gdm /run/runit/service/
fi

sudo usermod -aG tfenv epost

grep -qxF 'auth-polkit=false' /etc/NetworkManager/NetworkManager.conf || sudo tee -a /etc/NetworkManager/NetworkManager.conf >/dev/null << 'EOF'
auth-polkit=false
EOF
