#!/bin/bash
sudo pacman -Sy --needed base-devel --noconfirm;

which paru > /dev/null 2>&1;

if [ $? -ne 0 ];
then
  git clone https://aur.archlinux.org/paru-bin.git;
  cd paru-bin;
  makepkg -si --noconfirm;
  cd ..;
  rm -rf paru-bin;
fi

paru -S paru-bin --needed --noconfirm --skipreview;

sudo pacman -Sy --needed artix-archlinux-support --noconfirm

paru -S --needed --noconfirm --skipreview \
brave-bin \
exa \
fish \
gdm-runit \
gnome-control-center \
gnome-shell \
gnome-tweaks \
ispell \
openssh-runit \
neofetch \
pyenv \
tfenv \
ttf-fira-code;

if [[ $(cat /etc/passwd | grep epost | awk -F: '{print $7}') != '/usr/bin/fish' ]];
then
  chsh -s /usr/bin/fish;
fi

if [ ! -L /run/runit/service/sshd ];
then
  sudo ln -s /etc/runit/sv/sshd /run/runit/service/
fi

if [ ! -L /run/runit/service/gdm ];
then
  sudo ln -s /etc/runit/sv/gdm /run/runit/service/
fi
