#!/bin/bash
sudo pacman -Sy --needed base-devel --noconfirm;

which paru > /dev/null 2>&1;

if [ $? -ne 0 ];
then
  git clone https://aur.archlinux.org/paru-bin.git;
  cd paru-bin;
  makepkg -si --noconfirm;
  cd ..;
  rm -rf paru-bin;
fi

paru -S paru-bin --needed --noconfirm --skipreview;

paru -S --needed --noconfirm --skipreview \
exa \
fish \
openssh-runit \
neofetch \
pyenv \
tfenv;

if [ $SHELL != '/usr/bin/fish' ];
then
  chsh -s /usr/bin/fish;
fi

ln -s /etc/runit/sv/sshd /run/runit/service/
